export default {
  SET_LANGUAGES: "SET_LANGUAGES",
  SET_GROUPS: "SET_GROUPS",
  SET_SELECTED_GROUP_NAME: "SET_SELECTED_GROUP_NAME",
  SET_WORDS: "SET_WORDS",
  SET_WORDS_PAGES_COUNT: "SET_WORDS_PAGES_COUNT",
  SET_STILL_GETTING_WORDS: "SET_STILL_GETTING_WORDS",
  UPDATE_WORD: "UPDATE_WORD",
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_EXAMPLE_WORDS: "SET_EXAMPLE_WORDS",
};
