export default {
  SET_LANGUAGES: "SET_LANGUAGES",
  SET_GROUPS: "SET_GROUPS",
  SWITCH_LANGUAGE: "SWITCH_LANGUAGE",
  SET_SELECTED_GROUP_NAME: "SET_SELECTED_GROUP_NAME",
  SET_WORDS: "SET_WORDS",
  SET_WORDS_PAGE_COUNT: "SET_WORDS_PAGE_COUNT",
  SET_STILL_GETTING_WORDS: "SET_STILL_GETTING_WORDS",
  UPDATE_WORD: "UPDATE_WORD",
};
